# create data dictionary 

In [3]:
A=[1,2,3,4]

In [107]:
X=[]
Y=[]
for i in range(5):
    X.append(1*A)
Y = ['r','u','w','a','n']
R=True

In [108]:
data={
    'value':X,
    'name':Y,
    'logic':R
}

In [102]:
type(data)

dict

In [109]:
import json
with open('test.json', 'w') as fp:
    json.dump(data, fp)

In [110]:
with open("test.json", "r") as fload:
    Rdata = json.load(fload)

In [113]:
import pandas as pd
x = pd.Series()

/tmp/ipykernel_105464/965865595.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  x = pd.Series()


In [133]:
import numpy as np
A = [[[1,2],[3,4]]]
Arr=[]
Arr.append(A)
Arr.append(A)
Arr.append(A)
npArr = np.array(Arr)

# Lable encoding

In [61]:
import tensorflow as tf

original_indices = tf.constant([0,1,2,3,4,5,6,7,8,9])
depth = tf.constant(10)
one_hot_encoded = tf.one_hot(indices=original_indices, depth=depth)
type(depth)

tensorflow.python.framework.ops.EagerTensor

In [62]:
  print(one_hot_encoded)

tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]], shape=(10, 10), dtype=float32)


In [66]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
Y = ['ruwan','saman','kamal','siril','sumana']
Y = pd.array(Y)
Y = Y.reshape((len(Y), 1))
oe = OrdinalEncoder()
oe.fit(Y)
EnY = oe.transform(Y)
EnY

array([[1.],
       [2.],
       [0.],
       [3.],
       [4.]])

In [97]:
dirData = './Data'

def  encodeLable (dirData):
    mapping =[]
    for mamalName in os.listdir(dirData): 
        mapping.append(mamalName)

    mapping = pd.array(mapping)
    pdY = mapping.reshape((len(mapping), 1))
    oe = OrdinalEncoder()
    oe.fit(pdY)
    encY = oe.transform(pdY)
    labelY = { mapping[i]:int(encY[i]) for i in range(len(mapping))}
    return mapping, labelY


In [99]:
mapping, encodeY = encodeLable (dirData)
encodeY ['spotted Dolphin']


8

In [74]:
mapping

<StringArray>
[    'spotted Dolphin',        'Bearded Seal',  'Beluga White Whale',
  'Bottlenose Dolphin',       'Bowhead Whale',     'Clymene Dolphin',
      'Common Dolphin', 'BFalse Killer Whale',       'Finback Whale']
Length: 9, dtype: string